import com.android.build.api.artifact.SingleArtifact
import com.fongmi.gradle.AbiApkPackaging

plugins {
    alias libs.plugins.android.application
}

def localProps = new Properties()
rootProject.file('local.properties').withInputStream {
    localProps.load(it)
}

android {
    namespace = 'com.fongmi.android.tv'

    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        applicationId "com.cyj265.lanxingvod"
        minSdk 24
        targetSdk 37
        versionCode 585
        versionName "5.6.3"
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation": "$projectDir/schemas".toString(), "eventBusIndex": "com.fongmi.android.tv.event.EventIndex"]
            }
        }
    }

    flavorDimensions = ["device"]

    productFlavors {
        leanback {
            dimension "device"
        }
        mobile {
            dimension "device"
        }
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    signingConfigs {
        release {
            storeFile file(localProps['storeFile'])
            keyAlias localProps['keyAlias']
            keyPassword localProps['storePassword']
            storePassword localProps['storePassword']
        }
    }

    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            signingConfig = signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro', 'proguard-rules-media.pro'
        }
    }

    configurations.configureEach {
        exclude group: 'stax', module: 'stax-api'
        exclude group: 'xpp3', module: 'xpp3'
        exclude group: 'com.android.support'
        exclude group: 'io.antmedia', module: 'rtmp-client'
        resolutionStrategy {
            force libs.okhttp
            eachDependency { details ->
                if (details.requested.group == 'androidx.media3') {
                    details.useVersion libs.versions.media3.get()
                }
            }
        }
    }

    sourceSets {
        main {
            java {
                exclude 'com/fongmi/android/tv/player/mpv/MpvPlayerEffect.java'
                exclude 'com/fongmi/android/tv/player/effect/audio/MpvAudioEffectFilter.java'
                exclude 'com/fongmi/android/tv/player/effect/video/MpvVideoEffectController.java'
            }
        }
    }

    lint {
        disable 'UnsafeOptInUsageError'
        disable 'ExpiredTargetSdkVersion'
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

AbiApkPackaging.configure(project, SingleArtifact.APK.INSTANCE)

dependencies {
    implementation fileTree(dir: "libs", include: ["*.aar"])
    implementation project(':catvod')
    implementation project(':chaquo')
    implementation project(':quickjs')
    implementation libs.appcompat
    implementation libs.lifecycle.service
    implementation libs.media
    implementation libs.bundles.media3
    implementation libs.nextlib.media3ext
    implementation libs.exoplayer.hdr.utils
    implementation libs.palette
    implementation libs.recyclerview
    implementation libs.room.runtime
    implementation libs.splashscreen
    implementation libs.swiperefreshlayout
    implementation libs.viewpager2
    implementation libs.android.gif.drawable
    implementation libs.bundles.glide
    implementation libs.bundles.jupnp
    implementation libs.customactivityoncrash
    implementation libs.eventbus
    implementation libs.flexbox
    implementation libs.rtmp.client
    implementation libs.lottie
    implementation libs.material
    implementation libs.materialdesigncolors
    implementation libs.nanohttpd
    implementation libs.newpipeextractor
    implementation libs.permissionx
    implementation libs.simple.xml
    implementation libs.textdrawable
    implementation 'com.tencent.bugly:crashreport:4.1.9.3'
    implementation 'com.tencent.bugly:nativecrashreport:3.9.2'
    leanbackImplementation libs.leanback
    leanbackImplementation libs.androidautosize
    mobileImplementation libs.biometric
    mobileImplementation libs.zxing.android.embedded
    annotationProcessor libs.room.compiler
    annotationProcessor libs.eventbus.annotation.processor
    annotationProcessor libs.glide.compiler
    coreLibraryDesugaring libs.desugar
}
