plugins {
    alias libs.plugins.android.application
}

def localProps = new Properties()
def localPropsFile = rootProject.file('local.properties')
if (localPropsFile.exists()) {
    localPropsFile.withInputStream {
        localProps.load(it)
    }
}

def keystoreFile = rootProject.file('keystore.properties')
if (localPropsFile.exists()) {
    localPropsFile.withInputStream {
        localProps.load(it)
    }
}

android {
    namespace 'com.cyj265.lanxingvod'
    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        applicationId "com.cyj265.lanxingvod"
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()
        versionCode 598
        versionName "5.6.16"
        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation": "$projectDir/schemas"]
            }
        }
    }
}